import type { Config } from 'tailwindcss';
import typography from '@tailwindcss/typography';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: ['class', '[data-theme="high-contrast"]'],
  safelist: [
    'theme-paper',
    'theme-high-contrast',
    'theme-dos-blue',
    'theme-cyberpunk',
    'theme-solarized'
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Berkeley Mono', 'monospace'],
        mono: ['Berkeley Mono', 'monospace'],
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-out": {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        "zoom-in": {
          from: { transform: "scale(0.95)" },
          to: { transform: "scale(1)" },
        },
        "zoom-out": {
          from: { transform: "scale(1)" },
          to: { transform: "scale(0.95)" },
        },
        "slide-in-from-top": {
          from: { transform: "translateY(-100%)" },
          to: { transform: "translateY(0)" },
        },
        "slide-in-from-bottom": {
          from: { transform: "translateY(100%)" },
          to: { transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.2s ease-out",
        "fade-out": "fade-out 0.2s ease-in",
        "zoom-in": "zoom-in 0.2s ease-out",
        "zoom-out": "zoom-out 0.2s ease-in",
        "slide-in-from-top": "slide-in-from-top 0.2s ease-out",
        "slide-in-from-bottom": "slide-in-from-bottom 0.2s ease-out",
      },
    },
  },
  plugins: [
    typography,
    function({ addBase }: any) {
      addBase({
        ':root[class~="theme-high-contrast"]': {
          '--background': '0 0% 0%',
          '--foreground': '0 0% 100%',
          '--primary': '120 100% 50%',
          '--primary-foreground': '0 0% 0%',
          '--secondary': '0 0% 10%',
          '--secondary-foreground': '0 0% 100%',
          '--muted': '0 0% 15%',
          '--muted-foreground': '0 0% 63%',
          '--accent': '120 100% 50%',
          '--accent-foreground': '0 0% 0%',
          '--border': '0 0% 20%',
          '--input': '0 0% 20%',
          '--ring': '120 100% 50%',
          '--radius': '0.5rem',
        },
        ':root[class~="theme-paper"]': {
          '--background': '45 29% 97%',
          '--foreground': '20 14.3% 4.1%',
          '--primary': '24 9.8% 10%',
          '--primary-foreground': '60 9.1% 97.8%',
          '--secondary': '60 4.8% 95.9%',
          '--secondary-foreground': '24 9.8% 10%',
          '--muted': '60 4.8% 95.9%',
          '--muted-foreground': '25 5.3% 44.7%',
          '--accent': '60 4.8% 95.9%',
          '--accent-foreground': '24 9.8% 10%',
          '--border': '20 5.9% 90%',
          '--input': '20 5.9% 90%',
          '--ring': '24 5.4% 63.9%',
          '--radius': '0.5rem',
        },
        ':root[class~="theme-dos-blue"]': {
          '--background': '240 100% 25%',
          '--foreground': '0 0% 100%',
          '--primary': '180 100% 50%',
          '--primary-foreground': '240 100% 25%',
          '--secondary': '240 100% 20%',
          '--secondary-foreground': '0 0% 100%',
          '--muted': '240 100% 20%',
          '--muted-foreground': '0 0% 63%',
          '--accent': '180 100% 50%',
          '--accent-foreground': '240 100% 25%',
          '--border': '240 100% 33%',
          '--input': '240 100% 33%',
          '--ring': '180 100% 50%',
          '--radius': '0px',
        },
        ':root[class~="theme-cyberpunk"]': {
          '--background': '300 89% 5%',
          '--foreground': '300 100% 98%',
          '--primary': '326 100% 50%',
          '--primary-foreground': '300 0% 0%',
          '--secondary': '266 100% 64%',
          '--secondary-foreground': '300 0% 0%',
          '--muted': '300 50% 10%',
          '--muted-foreground': '300 50% 80%',
          '--accent': '326 100% 50%',
          '--accent-foreground': '300 0% 0%',
          '--border': '326 100% 50%',
          '--input': '300 50% 10%',
          '--ring': '326 100% 40%',
          '--radius': '0px',
        },
        ':root[class~="theme-solarized"]': {
          '--background': '44 87% 94%',
          '--foreground': '192 81% 14%',
          '--primary': '18 80% 44%',
          '--primary-foreground': '44 87% 94%',
          '--secondary': '44 87% 89%',
          '--secondary-foreground': '192 81% 14%',
          '--muted': '44 87% 89%',
          '--muted-foreground': '192 81% 40%',
          '--accent': '18 80% 44%',
          '--accent-foreground': '44 87% 94%',
          '--border': '18 80% 44%',
          '--input': '44 87% 89%',
          '--ring': '18 80% 34%',
          '--radius': '0.375rem',
        },
        ':root[class~="theme-dos"]': {
          '--background': '240 100% 26%',
          '--foreground': '0 0% 100%',
          '--card': '240 100% 26%',
          '--card-foreground': '0 0% 100%',
          '--popover': '240 100% 26%',
          '--popover-foreground': '0 0% 100%',
          '--primary': '180 100% 50%',
          '--primary-foreground': '240 100% 26%',
          '--secondary': '240 100% 20%',
          '--secondary-foreground': '0 0% 100%',
          '--muted': '240 100% 20%',
          '--muted-foreground': '0 0% 63%',
          '--accent': '180 100% 50%',
          '--accent-foreground': '240 100% 26%',
          '--destructive': '0 100% 67%',
          '--destructive-foreground': '0 0% 100%',
          '--border': '0 0% 100%',
          '--input': '240 100% 26%',
          '--ring': '180 100% 50%',
          '--radius': '0px',
        },
      });
    },
  ],
};

export default config;
